services: 
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPassword  
    restart: always
    ports:
      - "27017:27017" #Expose it on the default port
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro #Call the file in mongo-init to create roles/users

  script_import_csv:
    build: ./script_import
    environment:
      - MONGO_USER=adminUser
      - MONGO_PASS=adminPassword
    container_name: script_import_csv
    #command: tail -f /dev/null
    depends_on:
      - mongodb
    
volumes:
  mongo_data:
    driver: local
    